const mongoose = require('mongoose');
require('dotenv').config();
const { Course, Club, Event } = require('./models');

// ─── Feature Vector Generator ───────────────────
// 10 dimensions: [AI/ML, WebDev, DataScience, Cloud, Mobile, Cybersecurity, DevOps, Design, Business, Hardware]
function fv(weights) { return weights; }

// ═══════════════════════════════════════════════
// COURSES DATA — 40 courses (Indian pricing in ₹)
// ═══════════════════════════════════════════════
const courses = [
  // ─── AI / Machine Learning ────────────────────
  { title: 'Machine Learning Fundamentals', description: 'Master core ML concepts including regression, classification, clustering, and neural networks. Build real projects with Python and scikit-learn. Includes 8 hands-on projects and certificate.', type: 'course', category: 'AI/ML', tags: ['python', 'machine-learning', 'scikit-learn', 'beginner'], difficulty: 'beginner', duration: '8 weeks', price: 0, rating: 4.7, totalRatings: 2340, provider: 'Coursera (Andrew Ng)', skillsGained: ['Python', 'Machine Learning', 'Data Analysis'], featureVector: fv([0.95, 0.1, 0.6, 0.1, 0.0, 0.0, 0.1, 0.0, 0.1, 0.0]), enrollments: 15200, trending: true },
  { title: 'Deep Learning Specialization', description: 'Dive deep into neural networks, CNNs, RNNs, and transformers. Learn TensorFlow and build production-ready AI models. Industry recognised.', type: 'course', category: 'AI/ML', tags: ['deep-learning', 'tensorflow', 'neural-networks', 'advanced'], difficulty: 'advanced', duration: '16 weeks', price: 4099, rating: 4.9, totalRatings: 5600, provider: 'DeepLearning.AI', skillsGained: ['Deep Learning', 'TensorFlow', 'Neural Networks', 'Python'], featureVector: fv([1.0, 0.0, 0.5, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 28900, trending: true },
  { title: 'Natural Language Processing with Python', description: 'Learn text processing, sentiment analysis, chatbots, and large language models using NLTK, spaCy and HuggingFace transformers.', type: 'course', category: 'AI/ML', tags: ['nlp', 'python', 'text-analysis', 'intermediate', 'llm'], difficulty: 'intermediate', duration: '6 weeks', price: 2499, rating: 4.5, totalRatings: 1890, provider: 'Udemy', skillsGained: ['NLP', 'Python', 'Text Mining', 'HuggingFace'], featureVector: fv([0.9, 0.1, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]), enrollments: 8700, trending: false },
  { title: 'Computer Vision & Image Recognition', description: 'Build image classifiers, object detectors, and face recognition systems using OpenCV and PyTorch. YOLO, segmentation, and more.', type: 'course', category: 'AI/ML', tags: ['computer-vision', 'opencv', 'pytorch', 'intermediate', 'yolo'], difficulty: 'intermediate', duration: '10 weeks', price: 3249, rating: 4.6, totalRatings: 1200, provider: 'Udacity', skillsGained: ['Computer Vision', 'PyTorch', 'OpenCV', 'Object Detection'], featureVector: fv([0.95, 0.0, 0.3, 0.1, 0.1, 0.0, 0.0, 0.2, 0.0, 0.1]), enrollments: 6500, trending: true },
  { title: 'Generative AI & Prompt Engineering', description: 'Master ChatGPT, DALL-E, Stable Diffusion and learn professional prompt engineering. Build AI-powered apps using OpenAI API.', type: 'course', category: 'AI/ML', tags: ['generative-ai', 'chatgpt', 'prompt-engineering', 'openai', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 0, rating: 4.8, totalRatings: 9100, provider: 'Google DeepMind', skillsGained: ['Prompt Engineering', 'API Integration', 'AI Tools', 'ChatGPT'], featureVector: fv([0.9, 0.2, 0.4, 0.1, 0.0, 0.0, 0.0, 0.3, 0.2, 0.0]), enrollments: 41000, trending: true },
  { title: 'Reinforcement Learning: From Zero to Hero', description: 'Build AI agents that learn by doing using Q-learning, PPO, DDPG. Train game-playing bots and autonomous agents with OpenAI Gym.', type: 'course', category: 'AI/ML', tags: ['reinforcement-learning', 'python', 'openai-gym', 'advanced'], difficulty: 'advanced', duration: '12 weeks', price: 3799, rating: 4.4, totalRatings: 540, provider: 'Hugging Face', skillsGained: ['RL', 'Python', 'OpenAI Gym', 'Neural Networks'], featureVector: fv([1.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.1]), enrollments: 3200, trending: false },

  // ─── Web Development ──────────────────────────
  { title: 'Full Stack Web Development Bootcamp', description: 'Learn HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build 10+ real-world projects from scratch. Job-ready curriculum.', type: 'course', category: 'Web Dev', tags: ['html', 'css', 'javascript', 'react', 'nodejs', 'mongodb'], difficulty: 'beginner', duration: '12 weeks', price: 0, rating: 4.8, totalRatings: 8900, provider: 'freeCodeCamp', skillsGained: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB'], featureVector: fv([0.1, 1.0, 0.2, 0.2, 0.1, 0.0, 0.2, 0.3, 0.0, 0.0]), enrollments: 45000, trending: true },
  { title: 'React.js Advanced Patterns & Performance', description: 'Master hooks, context, render props, HOCs, code splitting, lazy loading, and React 18 concurrent features for production apps.', type: 'course', category: 'Web Dev', tags: ['react', 'javascript', 'frontend', 'advanced', 'performance'], difficulty: 'advanced', duration: '4 weeks', price: 2899, rating: 4.6, totalRatings: 2100, provider: 'Frontend Masters', skillsGained: ['React', 'JavaScript', 'Performance Optimization', 'TypeScript'], featureVector: fv([0.0, 0.95, 0.0, 0.1, 0.1, 0.0, 0.0, 0.2, 0.0, 0.0]), enrollments: 9800, trending: false },
  { title: 'Node.js API Design & Microservices', description: 'Build scalable REST APIs and microservices with Node.js, Express, and Docker. Auth, testing, rate limiting, caching.', type: 'course', category: 'Web Dev', tags: ['nodejs', 'express', 'api', 'microservices', 'intermediate'], difficulty: 'intermediate', duration: '6 weeks', price: 2099, rating: 4.5, totalRatings: 1750, provider: 'Pluralsight', skillsGained: ['Node.js', 'Express', 'REST API', 'Docker', 'JWT'], featureVector: fv([0.0, 0.85, 0.0, 0.4, 0.0, 0.1, 0.4, 0.0, 0.0, 0.0]), enrollments: 7200, trending: false },
  { title: 'JavaScript ES6+ Complete Guide', description: 'Deep dive into modern JavaScript — promises, async/await, modules, destructuring, functional programming, and TypeScript basics.', type: 'course', category: 'Web Dev', tags: ['javascript', 'es6', 'typescript', 'intermediate'], difficulty: 'intermediate', duration: '5 weeks', price: 1299, rating: 4.7, totalRatings: 4500, provider: 'Udemy', skillsGained: ['JavaScript', 'ES6+', 'Async Programming', 'TypeScript'], featureVector: fv([0.1, 0.9, 0.1, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]), enrollments: 18500, trending: true },
  { title: 'Vue.js 3 & Nuxt.js - The Complete Guide', description: 'Build fast, modern web apps with Vue 3 Composition API and Nuxt.js. Covers SSR, state management with Pinia, and deployment.', type: 'course', category: 'Web Dev', tags: ['vuejs', 'nuxt', 'javascript', 'frontend', 'intermediate'], difficulty: 'intermediate', duration: '7 weeks', price: 1999, rating: 4.5, totalRatings: 1100, provider: 'Udemy', skillsGained: ['Vue.js', 'Nuxt.js', 'SSR', 'Pinia'], featureVector: fv([0.0, 0.9, 0.0, 0.1, 0.1, 0.0, 0.0, 0.2, 0.0, 0.0]), enrollments: 5600, trending: false },

  // ─── Data Science ─────────────────────────────
  { title: 'Data Science with Python & Pandas', description: 'Learn data wrangling, visualization, and statistical analysis using Python, Pandas, NumPy, Seaborn and Matplotlib. Real datasets.', type: 'course', category: 'Data Science', tags: ['python', 'pandas', 'data-analysis', 'beginner', 'numpy'], difficulty: 'beginner', duration: '6 weeks', price: 0, rating: 4.6, totalRatings: 3800, provider: 'Kaggle', skillsGained: ['Python', 'Pandas', 'Data Visualization', 'NumPy'], featureVector: fv([0.4, 0.0, 1.0, 0.1, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0]), enrollments: 22000, trending: true },
  { title: 'SQL for Data Analytics', description: 'Master SQL queries, joins, subqueries, window functions, CTEs, and database optimization for analytics. Includes PostgreSQL & MySQL.', type: 'course', category: 'Data Science', tags: ['sql', 'database', 'analytics', 'beginner', 'postgresql'], difficulty: 'beginner', duration: '4 weeks', price: 0, rating: 4.5, totalRatings: 5200, provider: 'Mode Analytics', skillsGained: ['SQL', 'Database Design', 'Analytics', 'PostgreSQL'], featureVector: fv([0.1, 0.1, 0.9, 0.1, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 31000, trending: false },
  { title: 'Business Intelligence with Power BI', description: 'Create stunning interactive dashboards and reports in Power BI. DAX formulas, data modelling, and publishing to Power BI Service.', type: 'course', category: 'Data Science', tags: ['powerbi', 'business-intelligence', 'dashboard', 'intermediate'], difficulty: 'intermediate', duration: '5 weeks', price: 1799, rating: 4.4, totalRatings: 2200, provider: 'Microsoft Learn', skillsGained: ['Power BI', 'DAX', 'Data Modelling', 'Dashboards'], featureVector: fv([0.2, 0.0, 0.85, 0.0, 0.0, 0.0, 0.0, 0.3, 0.4, 0.0]), enrollments: 9800, trending: true },

  // ─── Cloud Computing ──────────────────────────
  { title: 'AWS Cloud Practitioner Certification', description: 'Prepare for AWS CLF-C02 exam — EC2, S3, Lambda, IAM, VPC, RDS, DynamoDB & cloud architecture. 300+ practice questions included.', type: 'course', category: 'Cloud', tags: ['aws', 'cloud', 'certification', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 1249, rating: 4.7, totalRatings: 6700, provider: 'AWS Training', skillsGained: ['AWS', 'Cloud Architecture', 'IAM', 'EC2', 'S3'], featureVector: fv([0.1, 0.2, 0.1, 1.0, 0.0, 0.2, 0.3, 0.0, 0.1, 0.0]), enrollments: 35000, trending: true },
  { title: 'Docker & Kubernetes for DevOps', description: 'Containerise applications with Docker, orchestrate with Kubernetes, set up CI/CD with Helm charts and deploy to production EKS.', type: 'course', category: 'Cloud', tags: ['docker', 'kubernetes', 'containers', 'intermediate', 'devops'], difficulty: 'intermediate', duration: '5 weeks', price: 2499, rating: 4.6, totalRatings: 2300, provider: 'Linux Foundation', skillsGained: ['Docker', 'Kubernetes', 'Container Orchestration', 'Helm'], featureVector: fv([0.0, 0.2, 0.0, 0.8, 0.0, 0.1, 0.9, 0.0, 0.0, 0.0]), enrollments: 12000, trending: true },
  { title: 'Google Cloud Professional Developer', description: 'Master GCP services: Cloud Run, BigQuery, Firestore, Pub/Sub, GKE, and Apigee. Prepare for the GCP Professional Developer exam.', type: 'course', category: 'Cloud', tags: ['gcp', 'google-cloud', 'certification', 'advanced'], difficulty: 'advanced', duration: '8 weeks', price: 3299, rating: 4.5, totalRatings: 890, provider: 'Google Cloud', skillsGained: ['GCP', 'BigQuery', 'Cloud Run', 'Firestore'], featureVector: fv([0.1, 0.2, 0.2, 0.95, 0.0, 0.0, 0.4, 0.0, 0.1, 0.0]), enrollments: 4500, trending: false },

  // ─── Mobile Development ───────────────────────
  { title: 'React Native — Build iOS & Android Apps', description: 'Build cross-platform mobile apps with React Native. Navigation, state management, camera, maps, push notifications & App Store deployment.', type: 'course', category: 'Mobile', tags: ['react-native', 'mobile', 'javascript', 'intermediate'], difficulty: 'intermediate', duration: '8 weeks', price: 2099, rating: 4.5, totalRatings: 1900, provider: 'Udemy', skillsGained: ['React Native', 'Mobile Development', 'JavaScript', 'Expo'], featureVector: fv([0.0, 0.4, 0.0, 0.1, 1.0, 0.0, 0.0, 0.2, 0.0, 0.0]), enrollments: 11000, trending: false },
  { title: 'Flutter & Dart Complete Masterclass', description: 'Build beautiful iOS and Android apps from one codebase. Firebase integration, state management with BLoC, and Play Store publishing.', type: 'course', category: 'Mobile', tags: ['flutter', 'dart', 'mobile', 'firebase', 'beginner'], difficulty: 'beginner', duration: '10 weeks', price: 1699, rating: 4.8, totalRatings: 3400, provider: 'Udemy', skillsGained: ['Flutter', 'Dart', 'Mobile UI', 'Firebase', 'BLoC'], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.95, 0.0, 0.0, 0.4, 0.0, 0.0]), enrollments: 16000, trending: true },

  // ─── Cybersecurity ────────────────────────────
  { title: 'Ethical Hacking & Penetration Testing', description: 'Learn ethical hacking — network scanning, exploitation, web app pentesting, privilege escalation. Kali Linux, Metasploit, Burp Suite.', type: 'course', category: 'Cybersecurity', tags: ['ethical-hacking', 'pentesting', 'kali-linux', 'intermediate', 'burp-suite'], difficulty: 'intermediate', duration: '8 weeks', price: 2899, rating: 4.7, totalRatings: 4100, provider: 'Offensive Security', skillsGained: ['Ethical Hacking', 'Penetration Testing', 'Burp Suite', 'Metasploit'], featureVector: fv([0.0, 0.1, 0.0, 0.2, 0.0, 1.0, 0.1, 0.0, 0.0, 0.1]), enrollments: 19000, trending: true },
  { title: 'Cybersecurity Fundamentals & Networking', description: 'Understand TCP/IP, encryption, firewalls, threat modelling, and security best practices. Prep for CompTIA Security+ exam.', type: 'course', category: 'Cybersecurity', tags: ['security', 'networking', 'comptia', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 0, rating: 4.4, totalRatings: 2800, provider: 'Cisco NetAcad', skillsGained: ['Security Fundamentals', 'Networking', 'CompTIA Security+'], featureVector: fv([0.0, 0.2, 0.0, 0.2, 0.0, 0.9, 0.1, 0.0, 0.0, 0.0]), enrollments: 14000, trending: false },

  // ─── DevOps ───────────────────────────────────
  { title: 'CI/CD Pipeline with GitHub Actions', description: 'Automate testing, building, and deployment with GitHub Actions. YAML workflows, secrets management, matrix builds, self-hosted runners.', type: 'course', category: 'DevOps', tags: ['cicd', 'github-actions', 'automation', 'intermediate'], difficulty: 'intermediate', duration: '3 weeks', price: 0, rating: 4.5, totalRatings: 1600, provider: 'GitHub', skillsGained: ['CI/CD', 'GitHub Actions', 'Automation', 'YAML'], featureVector: fv([0.0, 0.3, 0.0, 0.4, 0.0, 0.1, 1.0, 0.0, 0.0, 0.0]), enrollments: 8500, trending: false },
  { title: 'Terraform & Infrastructure as Code', description: 'Provision and manage cloud infrastructure using Terraform. AWS, GCP, Azure providers, modules, state management, and workspaces.', type: 'course', category: 'DevOps', tags: ['terraform', 'iac', 'devops', 'aws', 'intermediate'], difficulty: 'intermediate', duration: '5 weeks', price: 2199, rating: 4.6, totalRatings: 1100, provider: 'HashiCorp', skillsGained: ['Terraform', 'IaC', 'AWS', 'Cloud Provisioning'], featureVector: fv([0.0, 0.0, 0.0, 0.7, 0.0, 0.1, 0.95, 0.0, 0.0, 0.0]), enrollments: 6200, trending: true },

  // ─── Design ───────────────────────────────────
  { title: 'UI/UX Design Fundamentals with Figma', description: 'Learn user research, wireframing, prototyping, and visual design. Build a complete case study and add it to your portfolio. Google certified.', type: 'course', category: 'Design', tags: ['ui-ux', 'figma', 'design-thinking', 'beginner', 'portfolio'], difficulty: 'beginner', duration: '5 weeks', price: 0, rating: 4.7, totalRatings: 4200, provider: 'Google', skillsGained: ['UI Design', 'UX Research', 'Figma', 'Prototyping', 'User Testing'], featureVector: fv([0.0, 0.3, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0, 0.1, 0.0]), enrollments: 25000, trending: true },
  { title: 'Motion Design & UI Animation in After Effects', description: 'Create stunning UI micro-animations and motion graphics. Learn After Effects, Lottie export for React/React Native, and Rive animations.', type: 'course', category: 'Design', tags: ['motion-design', 'after-effects', 'animation', 'lottie', 'intermediate'], difficulty: 'intermediate', duration: '4 weeks', price: 2499, rating: 4.5, totalRatings: 780, provider: 'Skillshare', skillsGained: ['After Effects', 'Motion Design', 'Lottie', 'UI Animation'], featureVector: fv([0.0, 0.2, 0.5, 0.0, 0.0, 0.0, 0.0, 0.9, 0.1, 0.0]), enrollments: 3800, trending: true },

  // ─── DSA & Competitive Programming ────────────
  { title: 'Data Structures & Algorithms Masterclass', description: 'Complete DSA course covering arrays, linked lists, trees, graphs, dynamic programming, and problem-solving. 150+ LeetCode problems solved.', type: 'course', category: 'DSA', tags: ['dsa', 'algorithms', 'java', 'python', 'interview-prep'], difficulty: 'intermediate', duration: '10 weeks', price: 0, rating: 4.8, totalRatings: 7800, provider: 'freeCodeCamp', skillsGained: ['Data Structures', 'Algorithms', 'Problem Solving', 'Java', 'Python'], featureVector: fv([0.1, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 38000, trending: true },
  { title: 'System Design for SDE-2 & Above', description: 'Design scalable systems like Netflix, Uber, WhatsApp. Load balancing, caching, databases, message queues. Interview cracker.', type: 'course', category: 'DSA', tags: ['system-design', 'scalability', 'microservices', 'advanced'], difficulty: 'advanced', duration: '6 weeks', price: 3499, rating: 4.9, totalRatings: 3400, provider: 'ByteByteGo', skillsGained: ['System Design', 'Scalability', 'Architecture', 'Distributed Systems'], featureVector: fv([0.2, 0.3, 0.1, 0.7, 0.0, 0.1, 0.3, 0.0, 0.2, 0.0]), enrollments: 16000, trending: true },
];

// ═══════════════════════════════════════════════
// PRODUCTS DATA — 20 products (Indian pricing ₹)
// ═══════════════════════════════════════════════
const products = [
  { title: 'Python Crash Course — 3rd Edition', description: 'Best-selling Python book for beginners. Covers fundamentals, projects (game dev, data viz, web app with Django) and real-world coding practices.', type: 'product', category: 'AI/ML', tags: ['python', 'book', 'beginner'], difficulty: 'beginner', price: 699, rating: 4.8, totalRatings: 12000, provider: 'No Starch Press', skillsGained: ['Python'], featureVector: fv([0.7, 0.1, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), enrollments: 50000, trending: true },
  { title: 'Clean Code by Robert C. Martin', description: 'The definitive guide to writing readable, maintainable, and professional software. A must-read for every serious developer.', type: 'product', category: 'Web Dev', tags: ['clean-code', 'book', 'best-practices'], difficulty: 'intermediate', price: 899, rating: 4.7, totalRatings: 8500, provider: 'Prentice Hall', skillsGained: ['Clean Code', 'Software Design'], featureVector: fv([0.1, 0.5, 0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.1, 0.0]), enrollments: 35000, trending: false },
  { title: 'Keychron K2 Mechanical Keyboard', description: 'Compact wireless mechanical keyboard with RGB, hot-swappable switches, Mac/Windows compatibility. The #1 choice for developers & designers.', type: 'product', category: 'Hardware', tags: ['keyboard', 'mechanical', 'developer', 'hardware', 'wireless'], difficulty: 'beginner', price: 7499, rating: 4.6, totalRatings: 2300, provider: 'Keychron', skillsGained: [], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.9]), enrollments: 8000, trending: false },
  { title: 'GitHub Copilot — Student Plan', description: 'AI-powered code completion for free as a verified student. Suggests functions, tests, and entire files as you type across all major IDEs.', type: 'product', category: 'AI/ML', tags: ['ai', 'copilot', 'productivity', 'tools', 'free'], difficulty: 'beginner', price: 0, rating: 4.7, totalRatings: 7800, provider: 'GitHub', skillsGained: ['AI Tools', 'Productivity', 'Code Generation'], featureVector: fv([0.6, 0.5, 0.1, 0.1, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 55000, trending: true },
  { title: 'System Design Interview — Vol 1 & 2', description: 'Comprehensive guide to large-scale system design interviews. Covers 25+ real systems like URL shortener, Instagram, Ride-sharing, Chat apps.', type: 'product', category: 'DSA', tags: ['system-design', 'interview', 'book', 'advanced'], difficulty: 'advanced', price: 1199, rating: 4.9, totalRatings: 6700, provider: 'ByteByteGo', skillsGained: ['System Design', 'Scalability', 'Architecture'], featureVector: fv([0.1, 0.3, 0.1, 0.7, 0.0, 0.1, 0.3, 0.0, 0.2, 0.0]), enrollments: 28000, trending: true },
  { title: 'Sony WH-1000XM5 Noise-Cancelling Headphones', description: 'Industry-leading 30-hour ANC headphones with multipoint connection. Perfect for deep coding focus, online lectures, and late-night study sessions.', type: 'product', category: 'Hardware', tags: ['headphones', 'anc', 'sony', 'focus', 'hardware'], difficulty: 'beginner', price: 24990, rating: 4.8, totalRatings: 9800, provider: 'Sony', skillsGained: [], featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8]), enrollments: 40000, trending: true },
  { title: 'Raspberry Pi 5 Starter Kit', description: 'Complete kit with Raspberry Pi 5 (8GB), official case, touchscreen, 256GB SD, and a beginner project guide covering IoT, robotics, and Linux.', type: 'product', category: 'Hardware', tags: ['raspberry-pi', 'iot', 'hardware', 'beginner', 'robotics'], difficulty: 'beginner', price: 8999, rating: 4.6, totalRatings: 3400, provider: 'Raspberry Pi', skillsGained: ['IoT', 'Linux', 'Hardware', 'Python', 'Electronics'], featureVector: fv([0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0]), enrollments: 12000, trending: true },
  { title: 'Cracking the Coding Interview — 6th Ed.', description: '#1 guide for SDE interview preparation. 189 coding problems with detailed solutions, complexity analysis, and Big Tech interview frameworks.', type: 'product', category: 'DSA', tags: ['interview', 'dsa', 'book', 'intermediate', 'placement'], difficulty: 'intermediate', price: 849, rating: 4.8, totalRatings: 14000, provider: 'CareerCup', skillsGained: ['Data Structures', 'Algorithms', 'Problem Solving', 'Interview Skills'], featureVector: fv([0.2, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 65000, trending: true },
  { title: 'Figma Pro — Student License', description: 'Professional UI/UX design and prototyping tool. Free for verified students. Industry standard at Google, Meta, and Apple design teams.', type: 'product', category: 'Design', tags: ['figma', 'design', 'tools', 'free', 'student'], difficulty: 'beginner', price: 0, rating: 4.9, totalRatings: 11000, provider: 'Figma', skillsGained: ['Figma', 'UI Design', 'Prototyping', 'Design Systems'], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]), enrollments: 45000, trending: true },
  { title: 'LeetCode Premium — 3 Month Subscription', description: 'Access 2500+ problems, company-specific question sets (Google, Amazon, Microsoft), video solutions, and mock interview mode.', type: 'product', category: 'DSA', tags: ['leetcode', 'dsa', 'interview-prep', 'intermediate', 'placement'], difficulty: 'intermediate', price: 2499, rating: 4.6, totalRatings: 5600, provider: 'LeetCode', skillsGained: ['Algorithms', 'Data Structures', 'Problem Solving', 'Interview Prep'], featureVector: fv([0.1, 0.3, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 42000, trending: true },
  { title: 'Hands-On Machine Learning — 3rd Edition', description: 'Practical ML with scikit-learn, Keras and TensorFlow. Covers CNNs, RNNs, autoencoders, diffusion models, and production deployment.', type: 'product', category: 'AI/ML', tags: ['machine-learning', 'book', 'tensorflow', 'intermediate'], difficulty: 'intermediate', price: 1299, rating: 4.8, totalRatings: 7200, provider: "O'Reilly", skillsGained: ['Machine Learning', 'TensorFlow', 'Production ML', 'Keras'], featureVector: fv([0.95, 0.0, 0.5, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 32000, trending: false },
  { title: 'BenQ 27" 4K IPS Monitor', description: 'Eye-care 27-inch 4K IPS monitor with USB-C, HDR, 99% sRGB colour. Perfect for coding, UI design, and content creation. India warranty.', type: 'product', category: 'Hardware', tags: ['monitor', 'hardware', 'productivity', '4k', 'design'], difficulty: 'beginner', price: 28990, rating: 4.5, totalRatings: 4100, provider: 'BenQ', skillsGained: [], featureVector: fv([0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.85]), enrollments: 15000, trending: false },
  { title: 'JetBrains All Products Pack — Student', description: 'Free access to IntelliJ IDEA, PyCharm, WebStorm, DataGrip, GoLand and 10+ professional IDEs for verified students. Industry-grade tools.', type: 'product', category: 'Web Dev', tags: ['jetbrains', 'ide', 'tools', 'free', 'student'], difficulty: 'beginner', price: 0, rating: 4.8, totalRatings: 9200, provider: 'JetBrains', skillsGained: ['IntelliJ', 'PyCharm', 'WebStorm', 'Developer Tools'], featureVector: fv([0.3, 0.7, 0.2, 0.1, 0.1, 0.0, 0.2, 0.0, 0.0, 0.1]), enrollments: 48000, trending: true },
  { title: 'The Pragmatic Programmer — 20th Anniversary', description: 'Timeless wisdom on software craftsmanship. Covers orthogonality, DRY principle, metaprogramming, and building a long engineering career.', type: 'product', category: 'Web Dev', tags: ['programming', 'best-practices', 'book', 'software-engineering'], difficulty: 'intermediate', price: 999, rating: 4.7, totalRatings: 6400, provider: 'Addison-Wesley', skillsGained: ['Software Engineering', 'Clean Architecture', 'Best Practices'], featureVector: fv([0.2, 0.5, 0.1, 0.1, 0.0, 0.1, 0.2, 0.0, 0.1, 0.0]), enrollments: 22000, trending: false },
];

// ═══════════════════════════════════════════════
// CLUBS DATA — 12 clubs (India campus context)
// ═══════════════════════════════════════════════
const clubs = [
  { name: 'AI & Robotics Club', description: 'Explore AI, machine learning, and robotics through workshops, inter-college competitions, research projects, and industry expert talks. We participate in ROBOFEST, TechFest IIT Bombay & e-Yantra.', category: 'Technical', tags: ['ai', 'robotics', 'machine-learning', 'research', 'competitions'], memberCount: 120, meetingSchedule: 'Every Wednesday 5:00 PM', skillsGained: ['AI', 'Robotics', 'Python', 'Research', 'Arduino'], featureVector: fv([0.95, 0.1, 0.3, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5]) },
  { name: 'Web Development Society', description: 'Build websites and web apps together. Weekly code-along sessions, 48-hour hackathons, portfolio reviews, and freelancing workshops to earn while you learn.', category: 'Technical', tags: ['webdev', 'javascript', 'react', 'portfolio', 'freelancing'], memberCount: 200, meetingSchedule: 'Every Monday 6:00 PM', skillsGained: ['HTML', 'CSS', 'JavaScript', 'React', 'Teamwork'], featureVector: fv([0.0, 1.0, 0.0, 0.1, 0.1, 0.0, 0.0, 0.3, 0.0, 0.0]) },
  { name: 'Data Science & Analytics Circle', description: 'Analyse real Indian datasets, participate in Kaggle competitions, build data journalism projects, and master data storytelling to solve real social problems.', category: 'Technical', tags: ['data-science', 'kaggle', 'analytics', 'python', 'tableau'], memberCount: 85, meetingSchedule: 'Every Thursday 4:00 PM', skillsGained: ['Data Analysis', 'Python', 'Visualization', 'Statistics', 'Tableau'], featureVector: fv([0.4, 0.0, 1.0, 0.1, 0.0, 0.0, 0.0, 0.1, 0.1, 0.0]) },
  { name: 'Cybersecurity Guild', description: 'Learn ethical hacking, participate in national CTF challenges (HackTheBox, TryHackMe), and build security tools. We have represented the college at National Cyber Olympiad.', category: 'Technical', tags: ['cybersecurity', 'ctf', 'hacking', 'networking', 'ethical-hacking'], memberCount: 65, meetingSchedule: 'Every Friday 5:00 PM', skillsGained: ['Security', 'Networking', 'Ethical Hacking', 'CTF', 'Wireshark'], featureVector: fv([0.0, 0.1, 0.0, 0.2, 0.0, 1.0, 0.1, 0.0, 0.0, 0.1]) },
  { name: 'Open Source Contributors', description: 'Make meaningful open-source contributions. Git workflows, code review, participating in GSoC (Google Summer of Code), and getting mentored by FAANG engineers.', category: 'Technical', tags: ['opensource', 'github', 'git', 'gsoc', 'collaboration'], memberCount: 55, meetingSchedule: 'Every Saturday 11:00 AM', skillsGained: ['Git', 'Open Source', 'Collaboration', 'Code Review', 'GSoC'], featureVector: fv([0.1, 0.5, 0.0, 0.2, 0.0, 0.0, 0.5, 0.0, 0.1, 0.0]) },
  { name: 'E-Cell (Entrepreneurship Cell)', description: 'Turn ideas into startups! Pitch sessions, mentorship from IIT/IIM alumni, SEBI registered investor connections, and workshops on funding, patents, and business modelling.', category: 'Business', tags: ['startup', 'business', 'pitching', 'innovation', 'funding'], memberCount: 150, meetingSchedule: 'Every Tuesday 6:00 PM', skillsGained: ['Business Strategy', 'Pitching', 'Leadership', 'Financial Modelling'], featureVector: fv([0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0, 0.1, 0.9, 0.0]) },
  { name: 'UI/UX Design Lab', description: 'Practice design thinking, run weekly critique sessions, participate in Adobe Creative Jam, and build a portfolio that lands you at top design studios and product companies.', category: 'Creative', tags: ['design', 'ux', 'figma', 'creative', 'portfolio'], memberCount: 70, meetingSchedule: 'Every Wednesday 3:00 PM', skillsGained: ['UI Design', 'UX Research', 'Figma', 'Design Thinking', 'Portfolio'], featureVector: fv([0.0, 0.3, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0, 0.1, 0.0]) },
  { name: 'Competitive Programming Club', description: 'Sharpen your DSA skills through Codeforces/CodeChef contests, ICPC preparation (International Collegiate Programming Contest), and mock contests with editorial discussions.', category: 'Technical', tags: ['competitive-programming', 'dsa', 'algorithms', 'codeforces', 'icpc'], memberCount: 95, meetingSchedule: 'Every Saturday 2:00 PM', skillsGained: ['Algorithms', 'Data Structures', 'Problem Solving', 'C++', 'ICPC'], featureVector: fv([0.1, 0.3, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]) },
  { name: 'Cloud & DevOps Club', description: 'Get hands-on with AWS, GCP, and Azure through projects. Earn free cloud credits, prepare for certifications, and deploy production-grade applications as a team.', category: 'Technical', tags: ['cloud', 'aws', 'devops', 'azure', 'certifications'], memberCount: 60, meetingSchedule: 'Every Thursday 5:00 PM', skillsGained: ['AWS', 'Cloud Architecture', 'DevOps', 'Docker', 'Kubernetes'], featureVector: fv([0.1, 0.2, 0.0, 1.0, 0.0, 0.1, 0.3, 0.0, 0.1, 0.0]) },
  { name: 'Photography & Content Creation Club', description: 'Master DSLR/mirrorless photography, Adobe Lightroom, Premiere Pro, and build a personal brand on Instagram and YouTube. Official media partner for all college events.', category: 'Creative', tags: ['photography', 'video', 'content-creation', 'social-media', 'lightroom'], memberCount: 110, meetingSchedule: 'Every Sunday 10:00 AM', skillsGained: ['Photography', 'Video Editing', 'Content Creation', 'Lightroom', 'Premiere Pro'], featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.3, 0.0]) },
  { name: 'Research & Innovation Cell', description: 'Publish academic papers, apply for ICSSR/DST grants, collaborate with professors on funded research, and present at national conferences like ISTE and IEEE.', category: 'Academic', tags: ['research', 'publication', 'ieee', 'innovation', 'patents'], memberCount: 45, meetingSchedule: 'Every Tuesday 4:00 PM', skillsGained: ['Research', 'Academic Writing', 'LaTeX', 'Data Analysis', 'IEEE'], featureVector: fv([0.5, 0.2, 0.5, 0.1, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]) },
  { name: 'Finance & Fintech Club', description: 'Learn stock markets, algorithmic trading, blockchain, and fintech product development. Participate in BSE & NSE student investment challenge with virtual portfolios.', category: 'Business', tags: ['finance', 'fintech', 'stocks', 'blockchain', 'trading'], memberCount: 80, meetingSchedule: 'Every Monday 5:00 PM', skillsGained: ['Financial Analysis', 'Stock Markets', 'Fintech', 'Python for Finance', 'Blockchain'], featureVector: fv([0.3, 0.1, 0.3, 0.1, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0]) },
];

// ═══════════════════════════════════════════════
// EVENTS DATA — 14 events (India dates in 2026)
// ═══════════════════════════════════════════════
const events = [
  { title: 'HackCampus 2026 — 48-Hour Hackathon', description: '48-hour hackathon — build solutions to real campus and city problems using AI, IoT, or Web3. Prizes worth ₹1,00,000. Open to all branches. Food provided.', type: 'hackathon', date: new Date('2026-05-15'), tags: ['hackathon', 'coding', 'innovation', 'prizes'], skillsRelated: ['Full Stack', 'AI', 'Problem Solving', 'Teamwork'], location: 'Main Seminar Hall, Block A', capacity: 200, registered: 156, featureVector: fv([0.3, 0.5, 0.2, 0.2, 0.1, 0.0, 0.1, 0.2, 0.3, 0.0]) },
  { title: 'AI in Healthcare — Hands-On Workshop', description: 'Apply machine learning to real medical datasets — disease prediction, ECG analysis, and medical image segmentation with PyTorch. Certificate provided.', type: 'workshop', date: new Date('2026-04-28'), tags: ['ai', 'healthcare', 'workshop', 'machine-learning', 'python'], skillsRelated: ['Machine Learning', 'Python', 'Data Analysis', 'PyTorch'], location: 'CS Lab 204, Tech Block', capacity: 50, registered: 42, featureVector: fv([0.95, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]) },
  { title: 'Google Cloud Study Jam 2026', description: 'Official Google Cloud hands-on lab marathon. Complete skill badges in AI, data, and infrastructure. Top completers get Google swag and priority referrals.', type: 'workshop', date: new Date('2026-04-20'), tags: ['google-cloud', 'cloud', 'certification', 'hands-on', 'free'], skillsRelated: ['GCP', 'Cloud Architecture', 'BigQuery', 'ML on Cloud'], location: 'Innovation Hub, Block C', capacity: 80, registered: 67, featureVector: fv([0.1, 0.1, 0.0, 0.95, 0.0, 0.0, 0.3, 0.0, 0.1, 0.0]) },
  { title: 'Campus Tech Career Fair 2026', description: 'Meet recruiters from 30+ top companies — TCS, Infosys, Wipro, Razorpay, Zepto, Groww, and startups. On-spot offers for top profiles. Dress professionally.', type: 'career-fair', date: new Date('2026-05-05'), tags: ['career', 'placement', 'networking', 'resume', 'jobs'], skillsRelated: ['Communication', 'Networking', 'Interview Skills', 'Resume'], location: 'Convention Centre, Admin Block', capacity: 500, registered: 380, featureVector: fv([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0, 0.8, 0.0]) },
  { title: 'React & Next.js Full-Stack Bootcamp', description: 'Intensive 2-day bootcamp covering React 18, Next.js 14, App Router, Server Actions, Prisma ORM, and deployment on Vercel + AWS. Hands-on projects only.', type: 'workshop', date: new Date('2026-04-22'), tags: ['react', 'nextjs', 'fullstack', 'bootcamp', 'vercel'], skillsRelated: ['React', 'Next.js', 'Full Stack', 'Prisma', 'Deployment'], location: 'CS Lab A102', capacity: 40, registered: 38, featureVector: fv([0.0, 0.95, 0.0, 0.2, 0.1, 0.0, 0.2, 0.1, 0.0, 0.0]) },
  { title: 'National CTF Security Challenge', description: 'Capture The Flag cybersecurity competition across cryptography, forensics, web exploitation, and reverse engineering. National leaderboard. Cash prizes for top 3.', type: 'competition', date: new Date('2026-05-10'), tags: ['ctf', 'cybersecurity', 'hacking', 'competition', 'national'], skillsRelated: ['Cybersecurity', 'Cryptography', 'Reverse Engineering'], location: 'Online + CS Lab 101', capacity: 100, registered: 78, featureVector: fv([0.0, 0.1, 0.0, 0.1, 0.0, 1.0, 0.0, 0.0, 0.0, 0.1]) },
  { title: 'Kaggle Data Science Night', description: 'Team up and tackle a live Kaggle competition — real dataset, live leaderboard, and 3-hour sprint. Pizza for all participants. ₹10,000 prize pool.', type: 'competition', date: new Date('2026-05-02'), tags: ['kaggle', 'data-science', 'competition', 'teams', 'python'], skillsRelated: ['Data Science', 'Python', 'Machine Learning', 'Feature Engineering'], location: 'Library Makerspace', capacity: 60, registered: 45, featureVector: fv([0.5, 0.0, 0.95, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]) },
  { title: 'Resume & LinkedIn Masterclass', description: 'Craft a perfect tech resume (ATS-friendly) and LinkedIn profile that gets recruiter attention. Personalised 1-on-1 feedback from HR professionals at TCS, Infosys and Zomato.', type: 'workshop', date: new Date('2026-04-18'), tags: ['resume', 'linkedin', 'career', 'workshop', 'ats'], skillsRelated: ['Resume Writing', 'Personal Branding', 'Networking', 'Job Search'], location: 'Career Guidance Centre', capacity: 40, registered: 35, featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.0]) },
  { title: 'Mobile App Dev Marathon 2026', description: 'Build a complete mobile app in 24 hours. React Native and Flutter tracks. Top apps pitched to investors, winners get Google Play publishing support & ₹25,000 prize.', type: 'hackathon', date: new Date('2026-05-20'), tags: ['mobile', 'hackathon', 'react-native', 'flutter', 'investors'], skillsRelated: ['Mobile Development', 'React Native', 'Flutter', 'App Publishing'], location: 'Innovation Hub', capacity: 80, registered: 52, featureVector: fv([0.0, 0.3, 0.0, 0.0, 1.0, 0.0, 0.0, 0.3, 0.0, 0.0]) },
  { title: 'Open Source Contribution Day — GSoC Special', description: 'Make your first open source PR with guidance from GSoC alumni. Maintainers from Apache, Mozilla, and CNCF projects available as mentors. Certificate for contributions.', type: 'workshop', date: new Date('2026-05-08'), tags: ['opensource', 'github', 'gsoc', 'contribution', 'mentorship'], skillsRelated: ['Git', 'Open Source', 'Collaboration', 'GSoC'], location: 'CS Lab 101', capacity: 50, registered: 38, featureVector: fv([0.1, 0.4, 0.0, 0.2, 0.0, 0.0, 0.4, 0.0, 0.2, 0.0]) },
  { title: 'Startup Pitch Competition — Investor Special', description: 'Pitch your startup idea to a panel of VCs, angel investors, and IIT/IIM mentors. Winner gets ₹50,000 seed funding and 3 months of incubation support from E-Cell.', type: 'competition', date: new Date('2026-05-25'), tags: ['startup', 'pitching', 'funding', 'investors', 'incubation'], skillsRelated: ['Pitching', 'Business Strategy', 'Fundraising', 'Communication'], location: 'Business School Auditorium', capacity: 100, registered: 72, featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.95, 0.0]) },
  { title: 'Design Sprint — 5 Days in 1 Day', description: "Learn Google Ventures' 5-day design sprint methodology compressed into one intensive session. Build a clickable prototype and test it with real users. Certification from IDEO.", type: 'workshop', date: new Date('2026-06-01'), tags: ['design', 'ux', 'sprint', 'prototyping', 'ideo'], skillsRelated: ['Design Thinking', 'Prototyping', 'User Research', 'Figma'], location: 'Design Studio, Art Block', capacity: 30, registered: 18, featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.95, 0.2, 0.0]) },
  { title: 'Blockchain & Web3 Developer Summit', description: 'Learn Solidity, deploy smart contracts on Ethereum and Polygon, build a DeFi dApp. Industry speakers from Coinbase, CoinDCX, and WazirX. ₹5000 grant for best projects.', type: 'seminar', date: new Date('2026-04-25'), tags: ['blockchain', 'web3', 'solidity', 'ethereum', 'defi'], skillsRelated: ['Blockchain', 'Solidity', 'Web3', 'DeFi', 'Smart Contracts'], location: 'Lecture Hall B, Main Block', capacity: 150, registered: 89, featureVector: fv([0.1, 0.4, 0.0, 0.3, 0.0, 0.3, 0.0, 0.0, 0.3, 0.0]) },
  { title: 'IOT & Embedded Systems Workshop', description: 'Build IoT projects with Arduino, Raspberry Pi, and ESP32. Smart home automation, MQTT protocol, cloud integration with AWS IoT Core. Hardware kits provided on loan.', type: 'workshop', date: new Date('2026-06-10'), tags: ['iot', 'arduino', 'raspberry-pi', 'hardware', 'esp32'], skillsRelated: ['IoT', 'Embedded C', 'MQTT', 'AWS IoT', 'Sensors'], location: 'Electronics Lab, ECE Block', capacity: 35, registered: 22, featureVector: fv([0.2, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, 0.0, 0.0, 0.95]) },
];

// ═══════════════════════════════════════════════
// SEED FUNCTION
// ═══════════════════════════════════════════════
async function seedDatabase() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/campusiq';
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    await Course.deleteMany({});
    await Club.deleteMany({});
    await Event.deleteMany({});
    console.log('🗑️  Cleared existing data');

    const allCourses = [...courses, ...products];
    await Course.insertMany(allCourses);
    console.log(`📚 Inserted ${courses.length} courses + ${products.length} products = ${allCourses.length} total`);

    await Club.insertMany(clubs);
    console.log(`🏛️  Inserted ${clubs.length} clubs`);

    await Event.insertMany(events);
    console.log(`📅 Inserted ${events.length} events`);

    console.log(`
  ╔══════════════════════════════════════════════╗
  ║     ✅ Database Seeded Successfully!         ║
  ║                                              ║
  ║     📚 Courses:  ${courses.length}                          ║
  ║     🛒 Products: ${products.length}                          ║
  ║     🏛️  Clubs:    ${clubs.length}                          ║
  ║     📅 Events:   ${events.length}                          ║
  ║     ──────────────────────────               ║
  ║     📊 Total:    ${allCourses.length + clubs.length + events.length} items in DB             ║
  ║     💰 Currency: ₹ Indian Rupees            ║
  ╚══════════════════════════════════════════════╝
    `);

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed Error:', error.message);
    process.exit(1);
  }
}

seedDatabase();
