const mongoose = require('mongoose');
require('dotenv').config();
const { Course, Club, Event } = require('./models');

// ─── Feature Vector Generator ───────────────────
// 10 dimensions: [AI/ML, WebDev, DataScience, Cloud, Mobile, Cybersecurity, DevOps, Design, Business, Hardware]
function fv(weights) {
  return weights;
}

// ═══════════════════════════════════════════════
// COURSES DATA (30 courses)
// ═══════════════════════════════════════════════
const courses = [
  // ─── AI / Machine Learning ──────────────────
  { title: 'Machine Learning Fundamentals', description: 'Master core ML concepts including regression, classification, clustering, and neural networks. Build real projects with Python and scikit-learn.', type: 'course', category: 'AI/ML', tags: ['python', 'machine-learning', 'scikit-learn', 'beginner'], difficulty: 'beginner', duration: '8 weeks', price: 0, rating: 4.7, totalRatings: 2340, provider: 'Coursera', skillsGained: ['Python', 'Machine Learning', 'Data Analysis'], featureVector: fv([0.95, 0.1, 0.6, 0.1, 0.0, 0.0, 0.1, 0.0, 0.1, 0.0]), enrollments: 15200, trending: true },
  { title: 'Deep Learning Specialization', description: 'Dive deep into neural networks, CNNs, RNNs, and transformers. Learn TensorFlow and build production-ready AI models.', type: 'course', category: 'AI/ML', tags: ['deep-learning', 'tensorflow', 'neural-networks', 'advanced'], difficulty: 'advanced', duration: '16 weeks', price: 49, rating: 4.9, totalRatings: 5600, provider: 'DeepLearning.AI', skillsGained: ['Deep Learning', 'TensorFlow', 'Neural Networks', 'Python'], featureVector: fv([1.0, 0.0, 0.5, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 28900, trending: true },
  { title: 'Natural Language Processing with Python', description: 'Learn text processing, sentiment analysis, chatbots, and language models using NLTK and spaCy.', type: 'course', category: 'AI/ML', tags: ['nlp', 'python', 'text-analysis', 'intermediate'], difficulty: 'intermediate', duration: '6 weeks', price: 29, rating: 4.5, totalRatings: 1890, provider: 'Udemy', skillsGained: ['NLP', 'Python', 'Text Mining'], featureVector: fv([0.9, 0.1, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]), enrollments: 8700, trending: false },
  { title: 'Computer Vision & Image Recognition', description: 'Build image classifiers, object detectors, and face recognition systems using OpenCV and PyTorch.', type: 'course', category: 'AI/ML', tags: ['computer-vision', 'opencv', 'pytorch', 'intermediate'], difficulty: 'intermediate', duration: '10 weeks', price: 39, rating: 4.6, totalRatings: 1200, provider: 'Udacity', skillsGained: ['Computer Vision', 'PyTorch', 'OpenCV'], featureVector: fv([0.95, 0.0, 0.3, 0.1, 0.1, 0.0, 0.0, 0.2, 0.0, 0.1]), enrollments: 6500, trending: true },

  // ─── Web Development ────────────────────────
  { title: 'Full Stack Web Development Bootcamp', description: 'Learn HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build 10+ real-world projects from scratch.', type: 'course', category: 'Web Dev', tags: ['html', 'css', 'javascript', 'react', 'nodejs', 'mongodb', 'beginner'], difficulty: 'beginner', duration: '12 weeks', price: 0, rating: 4.8, totalRatings: 8900, provider: 'freeCodeCamp', skillsGained: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB'], featureVector: fv([0.1, 1.0, 0.2, 0.2, 0.1, 0.0, 0.2, 0.3, 0.0, 0.0]), enrollments: 45000, trending: true },
  { title: 'React.js Advanced Patterns', description: 'Master advanced React patterns — hooks, context, render props, HOCs, and performance optimization techniques.', type: 'course', category: 'Web Dev', tags: ['react', 'javascript', 'frontend', 'advanced'], difficulty: 'advanced', duration: '4 weeks', price: 35, rating: 4.6, totalRatings: 2100, provider: 'Frontend Masters', skillsGained: ['React', 'JavaScript', 'Performance Optimization'], featureVector: fv([0.0, 0.95, 0.0, 0.1, 0.1, 0.0, 0.0, 0.2, 0.0, 0.0]), enrollments: 9800, trending: false },
  { title: 'Node.js API Design & Microservices', description: 'Build scalable REST APIs and microservices with Node.js, Express, and Docker. Includes authentication and testing.', type: 'course', category: 'Web Dev', tags: ['nodejs', 'express', 'api', 'microservices', 'intermediate'], difficulty: 'intermediate', duration: '6 weeks', price: 25, rating: 4.5, totalRatings: 1750, provider: 'Pluralsight', skillsGained: ['Node.js', 'Express', 'REST API', 'Docker'], featureVector: fv([0.0, 0.85, 0.0, 0.4, 0.0, 0.1, 0.4, 0.0, 0.0, 0.0]), enrollments: 7200, trending: false },
  { title: 'CSS Mastery & Modern Layouts', description: 'Master Flexbox, Grid, animations, responsive design, and modern CSS architectures like BEM and utility-first.', type: 'course', category: 'Web Dev', tags: ['css', 'flexbox', 'grid', 'animations', 'beginner'], difficulty: 'beginner', duration: '3 weeks', price: 0, rating: 4.4, totalRatings: 3200, provider: 'YouTube', skillsGained: ['CSS', 'Responsive Design', 'Animations'], featureVector: fv([0.0, 0.8, 0.0, 0.0, 0.1, 0.0, 0.0, 0.7, 0.0, 0.0]), enrollments: 21000, trending: false },
  { title: 'JavaScript ES6+ Complete Guide', description: 'Deep dive into modern JavaScript — promises, async/await, modules, destructuring, and functional programming.', type: 'course', category: 'Web Dev', tags: ['javascript', 'es6', 'functional-programming', 'intermediate'], difficulty: 'intermediate', duration: '5 weeks', price: 15, rating: 4.7, totalRatings: 4500, provider: 'Udemy', skillsGained: ['JavaScript', 'ES6+', 'Async Programming'], featureVector: fv([0.1, 0.9, 0.1, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]), enrollments: 18500, trending: true },

  // ─── Data Science ───────────────────────────
  { title: 'Data Science with Python & Pandas', description: 'Learn data wrangling, visualization, and statistical analysis using Python, Pandas, and Matplotlib.', type: 'course', category: 'Data Science', tags: ['python', 'pandas', 'data-analysis', 'beginner'], difficulty: 'beginner', duration: '6 weeks', price: 0, rating: 4.6, totalRatings: 3800, provider: 'Kaggle', skillsGained: ['Python', 'Pandas', 'Data Visualization'], featureVector: fv([0.4, 0.0, 1.0, 0.1, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0]), enrollments: 22000, trending: true },
  { title: 'SQL for Data Analytics', description: 'Master SQL queries, joins, subqueries, window functions, and database optimization for analytics.', type: 'course', category: 'Data Science', tags: ['sql', 'database', 'analytics', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 0, rating: 4.5, totalRatings: 5200, provider: 'Khan Academy', skillsGained: ['SQL', 'Database Design', 'Analytics'], featureVector: fv([0.1, 0.1, 0.9, 0.1, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 31000, trending: false },
  { title: 'Statistical Learning & Probability', description: 'Understand probability distributions, hypothesis testing, regression analysis, and Bayesian statistics.', type: 'course', category: 'Data Science', tags: ['statistics', 'probability', 'math', 'intermediate'], difficulty: 'intermediate', duration: '8 weeks', price: 0, rating: 4.3, totalRatings: 1500, provider: 'MIT OCW', skillsGained: ['Statistics', 'Probability', 'Mathematical Modeling'], featureVector: fv([0.5, 0.0, 0.95, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]), enrollments: 8900, trending: false },

  // ─── Cloud Computing ────────────────────────
  { title: 'AWS Cloud Practitioner Certification', description: 'Prepare for AWS certification — learn EC2, S3, Lambda, IAM, and cloud architecture fundamentals.', type: 'course', category: 'Cloud', tags: ['aws', 'cloud', 'certification', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 15, rating: 4.7, totalRatings: 6700, provider: 'AWS Training', skillsGained: ['AWS', 'Cloud Architecture', 'IAM'], featureVector: fv([0.1, 0.2, 0.1, 1.0, 0.0, 0.2, 0.3, 0.0, 0.1, 0.0]), enrollments: 35000, trending: true },
  { title: 'Docker & Kubernetes Essentials', description: 'Containerize applications with Docker and orchestrate them with Kubernetes. Hands-on deployment labs.', type: 'course', category: 'Cloud', tags: ['docker', 'kubernetes', 'containers', 'intermediate'], difficulty: 'intermediate', duration: '5 weeks', price: 30, rating: 4.6, totalRatings: 2300, provider: 'Linux Foundation', skillsGained: ['Docker', 'Kubernetes', 'Container Orchestration'], featureVector: fv([0.0, 0.2, 0.0, 0.8, 0.0, 0.1, 0.9, 0.0, 0.0, 0.0]), enrollments: 12000, trending: true },

  // ─── Mobile Development ─────────────────────
  { title: 'React Native Mobile App Development', description: 'Build cross-platform mobile apps with React Native. Learn navigation, state management, and native APIs.', type: 'course', category: 'Mobile', tags: ['react-native', 'mobile', 'javascript', 'intermediate'], difficulty: 'intermediate', duration: '8 weeks', price: 25, rating: 4.5, totalRatings: 1900, provider: 'Udemy', skillsGained: ['React Native', 'Mobile Development', 'JavaScript'], featureVector: fv([0.0, 0.4, 0.0, 0.1, 1.0, 0.0, 0.0, 0.2, 0.0, 0.0]), enrollments: 11000, trending: false },
  { title: 'Flutter & Dart Complete Guide', description: 'Master Flutter framework and Dart language to build beautiful iOS and Android apps from one codebase.', type: 'course', category: 'Mobile', tags: ['flutter', 'dart', 'mobile', 'beginner'], difficulty: 'beginner', duration: '10 weeks', price: 20, rating: 4.8, totalRatings: 3400, provider: 'Udemy', skillsGained: ['Flutter', 'Dart', 'Mobile UI'], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.95, 0.0, 0.0, 0.4, 0.0, 0.0]), enrollments: 16000, trending: true },

  // ─── Cybersecurity ──────────────────────────
  { title: 'Ethical Hacking & Penetration Testing', description: 'Learn ethical hacking techniques — network scanning, vulnerability assessment, and exploitation with Kali Linux.', type: 'course', category: 'Cybersecurity', tags: ['ethical-hacking', 'pentesting', 'kali-linux', 'intermediate'], difficulty: 'intermediate', duration: '8 weeks', price: 35, rating: 4.7, totalRatings: 4100, provider: 'Offensive Security', skillsGained: ['Ethical Hacking', 'Penetration Testing', 'Network Security'], featureVector: fv([0.0, 0.1, 0.0, 0.2, 0.0, 1.0, 0.1, 0.0, 0.0, 0.1]), enrollments: 19000, trending: true },
  { title: 'Cybersecurity Fundamentals', description: 'Understand encryption, firewalls, threat modeling, and security best practices for web applications.', type: 'course', category: 'Cybersecurity', tags: ['security', 'encryption', 'web-security', 'beginner'], difficulty: 'beginner', duration: '4 weeks', price: 0, rating: 4.4, totalRatings: 2800, provider: 'Cisco', skillsGained: ['Security Fundamentals', 'Encryption', 'Firewalls'], featureVector: fv([0.0, 0.2, 0.0, 0.2, 0.0, 0.9, 0.1, 0.0, 0.0, 0.0]), enrollments: 14000, trending: false },

  // ─── DevOps ─────────────────────────────────
  { title: 'CI/CD Pipeline with GitHub Actions', description: 'Automate testing, building, and deployment with GitHub Actions. Learn YAML workflows and best practices.', type: 'course', category: 'DevOps', tags: ['cicd', 'github-actions', 'automation', 'intermediate'], difficulty: 'intermediate', duration: '3 weeks', price: 0, rating: 4.5, totalRatings: 1600, provider: 'GitHub', skillsGained: ['CI/CD', 'GitHub Actions', 'Automation'], featureVector: fv([0.0, 0.3, 0.0, 0.4, 0.0, 0.1, 1.0, 0.0, 0.0, 0.0]), enrollments: 8500, trending: false },
  { title: 'Linux System Administration', description: 'Master the Linux command line, shell scripting, process management, and server configuration.', type: 'course', category: 'DevOps', tags: ['linux', 'bash', 'sysadmin', 'beginner'], difficulty: 'beginner', duration: '6 weeks', price: 0, rating: 4.6, totalRatings: 3900, provider: 'Linux Foundation', skillsGained: ['Linux', 'Bash', 'System Administration'], featureVector: fv([0.0, 0.1, 0.0, 0.3, 0.0, 0.2, 0.85, 0.0, 0.0, 0.1]), enrollments: 17000, trending: false },

  // ─── Design ─────────────────────────────────
  { title: 'UI/UX Design Fundamentals', description: 'Learn user research, wireframing, prototyping, and visual design principles using Figma.', type: 'course', category: 'Design', tags: ['ui-ux', 'figma', 'design-thinking', 'beginner'], difficulty: 'beginner', duration: '5 weeks', price: 0, rating: 4.7, totalRatings: 4200, provider: 'Google', skillsGained: ['UI Design', 'UX Research', 'Figma', 'Prototyping'], featureVector: fv([0.0, 0.3, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0, 0.1, 0.0]), enrollments: 25000, trending: true },
  { title: 'Design Systems & Component Libraries', description: 'Build scalable design systems with tokens, components, and documentation for consistent team collaboration.', type: 'course', category: 'Design', tags: ['design-systems', 'components', 'figma', 'advanced'], difficulty: 'advanced', duration: '4 weeks', price: 40, rating: 4.4, totalRatings: 890, provider: 'Skillshare', skillsGained: ['Design Systems', 'Component Libraries', 'Documentation'], featureVector: fv([0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.1, 0.0]), enrollments: 4200, trending: false },
];

// ═══════════════════════════════════════════════
// PRODUCTS DATA (20 products)
// ═══════════════════════════════════════════════
const products = [
  { title: 'Python Crash Course (Book)', description: 'Best-selling Python book for beginners. Covers basics, projects (game, data viz, web app), and best practices.', type: 'product', category: 'AI/ML', tags: ['python', 'book', 'beginner'], difficulty: 'beginner', price: 25, rating: 4.8, totalRatings: 12000, provider: 'No Starch Press', skillsGained: ['Python'], featureVector: fv([0.7, 0.1, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), enrollments: 50000, trending: true },
  { title: 'Clean Code by Robert C. Martin', description: 'The definitive guide to writing readable, maintainable, and professional software code.', type: 'product', category: 'Web Dev', tags: ['clean-code', 'book', 'best-practices', 'intermediate'], difficulty: 'intermediate', price: 30, rating: 4.7, totalRatings: 8500, provider: 'Prentice Hall', skillsGained: ['Clean Code', 'Software Design'], featureVector: fv([0.1, 0.5, 0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.1, 0.0]), enrollments: 35000, trending: false },
  { title: 'Mechanical Keyboard (Developer Edition)', description: 'Ergonomic mechanical keyboard with programmable keys, RGB backlighting, and Cherry MX switches for coding comfort.', type: 'product', category: 'Hardware', tags: ['keyboard', 'ergonomic', 'developer', 'hardware'], difficulty: 'beginner', price: 89, rating: 4.6, totalRatings: 2300, provider: 'Keychron', skillsGained: [], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.9]), enrollments: 8000, trending: false },
  { title: 'VS Code Pro Extension Pack', description: 'Curated collection of 15 must-have VS Code extensions for full-stack development — linting, formatting, debugging.', type: 'product', category: 'Web Dev', tags: ['vscode', 'tools', 'extensions', 'beginner'], difficulty: 'beginner', price: 0, rating: 4.8, totalRatings: 15000, provider: 'Microsoft', skillsGained: ['VS Code', 'Developer Tools'], featureVector: fv([0.1, 0.8, 0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.0, 0.1]), enrollments: 60000, trending: true },
  { title: 'System Design Interview Book', description: 'Comprehensive guide to system design interviews — load balancing, caching, databases, and scalability patterns.', type: 'product', category: 'Cloud', tags: ['system-design', 'interview', 'book', 'advanced'], difficulty: 'advanced', price: 35, rating: 4.9, totalRatings: 6700, provider: 'ByteByteGo', skillsGained: ['System Design', 'Scalability', 'Architecture'], featureVector: fv([0.1, 0.3, 0.1, 0.7, 0.0, 0.1, 0.3, 0.0, 0.2, 0.0]), enrollments: 28000, trending: true },
  { title: 'Noise-Cancelling Headphones', description: 'Studio-quality noise-cancelling headphones perfect for focused coding sessions and online learning.', type: 'product', category: 'Hardware', tags: ['headphones', 'focus', 'hardware'], difficulty: 'beginner', price: 65, rating: 4.5, totalRatings: 9800, provider: 'Sony', skillsGained: [], featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8]), enrollments: 40000, trending: false },
  { title: 'GitHub Copilot Subscription', description: 'AI-powered code completion tool that suggests entire code blocks, functions, and tests as you type.', type: 'product', category: 'AI/ML', tags: ['ai', 'copilot', 'productivity', 'tools'], difficulty: 'beginner', price: 10, rating: 4.7, totalRatings: 7800, provider: 'GitHub', skillsGained: ['AI Tools', 'Productivity'], featureVector: fv([0.6, 0.5, 0.1, 0.1, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 55000, trending: true },
  { title: 'Raspberry Pi 5 Starter Kit', description: 'Complete starter kit with Raspberry Pi 5, case, SD card, and project guide for hardware/IoT projects.', type: 'product', category: 'Hardware', tags: ['raspberry-pi', 'iot', 'hardware', 'beginner'], difficulty: 'beginner', price: 75, rating: 4.6, totalRatings: 3400, provider: 'Raspberry Pi', skillsGained: ['IoT', 'Linux', 'Hardware'], featureVector: fv([0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0]), enrollments: 12000, trending: true },
  { title: 'Cracking the Coding Interview', description: 'The #1 coding interview preparation book — 189 programming problems and detailed solutions.', type: 'product', category: 'Web Dev', tags: ['interview', 'dsa', 'book', 'intermediate'], difficulty: 'intermediate', price: 28, rating: 4.8, totalRatings: 14000, provider: 'CareerCup', skillsGained: ['Data Structures', 'Algorithms', 'Problem Solving'], featureVector: fv([0.2, 0.4, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 65000, trending: true },
  { title: 'Figma Pro License', description: 'Professional design tool for UI/UX design, prototyping, and team collaboration. Industry standard.', type: 'product', category: 'Design', tags: ['figma', 'design', 'tools', 'beginner'], difficulty: 'beginner', price: 12, rating: 4.9, totalRatings: 11000, provider: 'Figma', skillsGained: ['Figma', 'UI Design'], featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]), enrollments: 45000, trending: true },
  { title: 'Postman API Testing Tool', description: 'Industry-standard API testing platform. Create, test, and document REST APIs with automated workflows.', type: 'product', category: 'Web Dev', tags: ['postman', 'api', 'testing', 'tools'], difficulty: 'beginner', price: 0, rating: 4.7, totalRatings: 8900, provider: 'Postman', skillsGained: ['API Testing', 'REST APIs'], featureVector: fv([0.0, 0.7, 0.0, 0.2, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0]), enrollments: 38000, trending: false },
  { title: 'LeetCode Premium Subscription', description: 'Access premium coding problems, company-specific questions, and detailed video solutions for interview prep.', type: 'product', category: 'Web Dev', tags: ['leetcode', 'dsa', 'interview-prep', 'intermediate'], difficulty: 'intermediate', price: 35, rating: 4.6, totalRatings: 5600, provider: 'LeetCode', skillsGained: ['Algorithms', 'Data Structures', 'Problem Solving'], featureVector: fv([0.1, 0.3, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]), enrollments: 42000, trending: true },
  { title: 'Hands-On Machine Learning (Book)', description: 'Practical ML book covering scikit-learn and TensorFlow with real-world projects and production deployment.', type: 'product', category: 'AI/ML', tags: ['machine-learning', 'book', 'tensorflow', 'intermediate'], difficulty: 'intermediate', price: 45, rating: 4.8, totalRatings: 7200, provider: "O'Reilly", skillsGained: ['Machine Learning', 'TensorFlow', 'Production ML'], featureVector: fv([0.95, 0.0, 0.5, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0]), enrollments: 32000, trending: false },
  { title: 'Ultrawide Monitor 34"', description: '34-inch curved ultrawide monitor with 4K resolution — ideal for multitasking, coding, and design work.', type: 'product', category: 'Hardware', tags: ['monitor', 'hardware', 'productivity'], difficulty: 'beginner', price: 350, rating: 4.5, totalRatings: 4100, provider: 'Samsung', skillsGained: [], featureVector: fv([0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.85]), enrollments: 15000, trending: false },
  { title: 'Cloud Computing Concepts (Book)', description: 'Essential guide to cloud architectures, AWS, Azure, GCP, serverless, and microservices patterns.', type: 'product', category: 'Cloud', tags: ['cloud', 'book', 'aws', 'architecture'], difficulty: 'intermediate', price: 40, rating: 4.4, totalRatings: 2100, provider: 'Manning', skillsGained: ['Cloud Architecture', 'AWS', 'Serverless'], featureVector: fv([0.1, 0.1, 0.0, 0.95, 0.0, 0.1, 0.3, 0.0, 0.1, 0.0]), enrollments: 9500, trending: false },
];

// ═══════════════════════════════════════════════
// CLUBS DATA (15 clubs)
// ═══════════════════════════════════════════════
const clubs = [
  { name: 'AI & Robotics Club', description: 'Explore artificial intelligence, machine learning, and robotics through workshops, competitions, and research projects.', category: 'Technical', tags: ['ai', 'robotics', 'machine-learning', 'research'], memberCount: 120, meetingSchedule: 'Every Wednesday 5 PM', skillsGained: ['AI', 'Robotics', 'Python', 'Research'], featureVector: fv([0.95, 0.1, 0.3, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5]) },
  { name: 'Web Development Society', description: 'Build websites and web apps together. Weekly code-along sessions, hackathons, and portfolio reviews.', category: 'Technical', tags: ['webdev', 'javascript', 'react', 'portfolio'], memberCount: 200, meetingSchedule: 'Every Monday 6 PM', skillsGained: ['HTML', 'CSS', 'JavaScript', 'React', 'Teamwork'], featureVector: fv([0.0, 1.0, 0.0, 0.1, 0.1, 0.0, 0.0, 0.3, 0.0, 0.0]) },
  { name: 'Data Science Circle', description: 'Analyze real datasets, participate in Kaggle competitions, and learn data storytelling techniques.', category: 'Technical', tags: ['data-science', 'kaggle', 'analytics', 'python'], memberCount: 85, meetingSchedule: 'Every Thursday 4 PM', skillsGained: ['Data Analysis', 'Python', 'Visualization', 'Statistics'], featureVector: fv([0.4, 0.0, 1.0, 0.1, 0.0, 0.0, 0.0, 0.1, 0.1, 0.0]) },
  { name: 'Cybersecurity Guild', description: 'Learn ethical hacking, participate in CTF challenges, and stay updated on the latest security vulnerabilities.', category: 'Technical', tags: ['cybersecurity', 'ctf', 'hacking', 'networking'], memberCount: 65, meetingSchedule: 'Every Friday 5 PM', skillsGained: ['Security', 'Networking', 'Ethical Hacking'], featureVector: fv([0.0, 0.1, 0.0, 0.2, 0.0, 1.0, 0.1, 0.0, 0.0, 0.1]) },
  { name: 'Open Source Contributors', description: 'Contribute to real open-source projects on GitHub. Learn Git workflows, code review, and collaboration.', category: 'Technical', tags: ['opensource', 'github', 'git', 'collaboration'], memberCount: 55, meetingSchedule: 'Every Saturday 11 AM', skillsGained: ['Git', 'Open Source', 'Collaboration', 'Code Review'], featureVector: fv([0.1, 0.5, 0.0, 0.2, 0.0, 0.0, 0.5, 0.0, 0.1, 0.0]) },
  { name: 'Entrepreneurship Cell', description: 'Turn ideas into startups. Pitch sessions, mentorship from industry leaders, and startup funding workshops.', category: 'Business', tags: ['startup', 'business', 'pitching', 'innovation'], memberCount: 150, meetingSchedule: 'Every Tuesday 6 PM', skillsGained: ['Business Strategy', 'Pitching', 'Leadership'], featureVector: fv([0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0, 0.1, 0.9, 0.0]) },
  { name: 'Design & UX Lab', description: 'Practice UI/UX design, run design sprints, and critique each other\'s work in a supportive community.', category: 'Creative', tags: ['design', 'ux', 'figma', 'creative'], memberCount: 70, meetingSchedule: 'Every Wednesday 3 PM', skillsGained: ['UI Design', 'UX Research', 'Figma', 'Design Thinking'], featureVector: fv([0.0, 0.3, 0.0, 0.0, 0.1, 0.0, 0.0, 1.0, 0.1, 0.0]) },
  { name: 'Competitive Programming Club', description: 'Sharpen DSA skills through competitive programming contests, problem-solving sessions, and interview prep.', category: 'Technical', tags: ['competitive-programming', 'dsa', 'algorithms', 'contests'], memberCount: 95, meetingSchedule: 'Every Saturday 2 PM', skillsGained: ['Algorithms', 'Data Structures', 'Problem Solving'], featureVector: fv([0.1, 0.3, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0]) },
  { name: 'Cloud Computing Club', description: 'Get hands-on with AWS, GCP, and Azure. Work on cloud certifications and build scalable applications.', category: 'Technical', tags: ['cloud', 'aws', 'azure', 'certifications'], memberCount: 60, meetingSchedule: 'Every Thursday 5 PM', skillsGained: ['AWS', 'Cloud Architecture', 'Certifications'], featureVector: fv([0.1, 0.2, 0.0, 1.0, 0.0, 0.1, 0.3, 0.0, 0.1, 0.0]) },
  { name: 'Photography & Videography', description: 'Capture campus life through lens. Learn photography, video editing, and content creation for social media.', category: 'Creative', tags: ['photography', 'video', 'content-creation', 'social-media'], memberCount: 110, meetingSchedule: 'Every Sunday 10 AM', skillsGained: ['Photography', 'Video Editing', 'Content Creation'], featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.3, 0.0]) },
];

// ═══════════════════════════════════════════════
// EVENTS DATA (15 events)
// ═══════════════════════════════════════════════
const events = [
  { title: 'HackCampus 2026', description: '48-hour hackathon — build innovative solutions to real-world campus problems. Prizes worth $5000.', type: 'hackathon', date: new Date('2026-05-15'), tags: ['hackathon', 'coding', 'innovation', 'prizes'], skillsRelated: ['Full Stack', 'Problem Solving', 'Teamwork'], location: 'Main Auditorium', capacity: 200, registered: 156, featureVector: fv([0.3, 0.5, 0.2, 0.2, 0.1, 0.0, 0.1, 0.2, 0.3, 0.0]) },
  { title: 'AI in Healthcare Workshop', description: 'Hands-on workshop on applying machine learning to healthcare data — disease prediction, medical imaging.', type: 'workshop', date: new Date('2026-04-28'), tags: ['ai', 'healthcare', 'workshop', 'machine-learning'], skillsRelated: ['Machine Learning', 'Python', 'Data Analysis'], location: 'CS Lab 204', capacity: 50, registered: 42, featureVector: fv([0.95, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]) },
  { title: 'Google Cloud Study Jam', description: 'Official Google Cloud hands-on lab session. Complete quests to earn Google Cloud skill badges.', type: 'workshop', date: new Date('2026-04-20'), tags: ['google-cloud', 'cloud', 'certification', 'hands-on'], skillsRelated: ['GCP', 'Cloud Architecture', 'DevOps'], location: 'Innovation Hub', capacity: 80, registered: 67, featureVector: fv([0.1, 0.1, 0.0, 0.95, 0.0, 0.0, 0.3, 0.0, 0.1, 0.0]) },
  { title: 'Tech Career Fair 2026', description: 'Meet recruiters from top tech companies — Google, Amazon, Microsoft, startups. Bring your resume!', type: 'career-fair', date: new Date('2026-05-05'), tags: ['career', 'jobs', 'networking', 'resume'], skillsRelated: ['Communication', 'Networking', 'Interview Skills'], location: 'Convention Center', capacity: 500, registered: 380, featureVector: fv([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0, 0.8, 0.0]) },
  { title: 'Web3 & Blockchain Seminar', description: 'Learn about decentralized applications, smart contracts, and the future of Web3 from industry experts.', type: 'seminar', date: new Date('2026-04-25'), tags: ['web3', 'blockchain', 'crypto', 'seminar'], skillsRelated: ['Blockchain', 'Smart Contracts', 'Solidity'], location: 'Lecture Hall B', capacity: 150, registered: 89, featureVector: fv([0.1, 0.4, 0.0, 0.3, 0.0, 0.3, 0.0, 0.0, 0.3, 0.0]) },
  { title: 'CTF Security Challenge', description: 'Capture The Flag cybersecurity competition. Solve challenges in cryptography, forensics, and web exploitation.', type: 'competition', date: new Date('2026-05-10'), tags: ['ctf', 'cybersecurity', 'competition', 'hacking'], skillsRelated: ['Cybersecurity', 'Cryptography', 'Problem Solving'], location: 'Online + CS Lab', capacity: 100, registered: 78, featureVector: fv([0.0, 0.1, 0.0, 0.1, 0.0, 1.0, 0.0, 0.0, 0.0, 0.1]) },
  { title: 'Design Sprint Workshop', description: 'Learn Google Ventures\' 5-day design sprint methodology compressed into one intensive day.', type: 'workshop', date: new Date('2026-04-22'), tags: ['design', 'ux', 'sprint', 'prototyping'], skillsRelated: ['Design Thinking', 'Prototyping', 'User Research'], location: 'Design Studio', capacity: 30, registered: 28, featureVector: fv([0.0, 0.2, 0.0, 0.0, 0.1, 0.0, 0.0, 0.95, 0.2, 0.0]) },
  { title: 'Data Science Kaggle Night', description: 'Team up and tackle a live Kaggle competition. Mentors available. Pizza and prizes for top teams.', type: 'competition', date: new Date('2026-05-02'), tags: ['kaggle', 'data-science', 'competition', 'teams'], skillsRelated: ['Data Science', 'Python', 'Machine Learning'], location: 'Library Makerspace', capacity: 60, registered: 45, featureVector: fv([0.5, 0.0, 0.95, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0]) },
  { title: 'Resume & LinkedIn Workshop', description: 'Craft a perfect tech resume and LinkedIn profile. Get personalized feedback from HR professionals.', type: 'workshop', date: new Date('2026-04-18'), tags: ['resume', 'linkedin', 'career', 'workshop'], skillsRelated: ['Resume Writing', 'Personal Branding', 'Networking'], location: 'Career Center', capacity: 40, registered: 35, featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.0]) },
  { title: 'Mobile App Dev Marathon', description: 'Build a complete mobile app in 24 hours. React Native and Flutter tracks available. Top apps get published.', type: 'hackathon', date: new Date('2026-05-20'), tags: ['mobile', 'hackathon', 'react-native', 'flutter'], skillsRelated: ['Mobile Development', 'React Native', 'Flutter'], location: 'Innovation Hub', capacity: 80, registered: 52, featureVector: fv([0.0, 0.3, 0.0, 0.0, 1.0, 0.0, 0.0, 0.3, 0.0, 0.0]) },
  { title: 'Open Source Contribution Day', description: 'Make your first (or 100th) open source contribution. Maintainers from popular repos guide you through PRs.', type: 'workshop', date: new Date('2026-05-08'), tags: ['opensource', 'github', 'git', 'contribution'], skillsRelated: ['Git', 'Open Source', 'Collaboration'], location: 'CS Lab 101', capacity: 50, registered: 38, featureVector: fv([0.1, 0.4, 0.0, 0.2, 0.0, 0.0, 0.4, 0.0, 0.2, 0.0]) },
  { title: 'Startup Pitch Competition', description: 'Pitch your startup idea to a panel of investors and mentors. Win mentorship and seed funding.', type: 'competition', date: new Date('2026-05-25'), tags: ['startup', 'pitching', 'business', 'competition'], skillsRelated: ['Pitching', 'Business Strategy', 'Communication'], location: 'Business School Auditorium', capacity: 100, registered: 72, featureVector: fv([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.95, 0.0]) },
];

// ═══════════════════════════════════════════════
// SEED FUNCTION
// ═══════════════════════════════════════════════
async function seedDatabase() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/campusiq';
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Course.deleteMany({});
    await Club.deleteMany({});
    await Event.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Insert courses and products
    const allCourses = [...courses, ...products];
    await Course.insertMany(allCourses);
    console.log(`📚 Inserted ${allCourses.length} courses & products`);

    // Insert clubs
    await Club.insertMany(clubs);
    console.log(`🏛️  Inserted ${clubs.length} clubs`);

    // Insert events
    await Event.insertMany(events);
    console.log(`📅 Inserted ${events.length} events`);

    console.log(`
  ╔══════════════════════════════════════════╗
  ║     ✅ Database Seeded Successfully      ║
  ║                                          ║
  ║     📚 Courses:  ${courses.length}                       ║
  ║     🛒 Products: ${products.length}                       ║
  ║     🏛️  Clubs:    ${clubs.length}                       ║
  ║     📅 Events:   ${events.length}                       ║
  ║     ─────────────────────                ║
  ║     📊 Total:    ${allCourses.length + clubs.length + events.length}                       ║
  ╚══════════════════════════════════════════╝
    `);

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed Error:', error.message);
    process.exit(1);
  }
}

seedDatabase();
